<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <RetrieveMulderDetails_Response>
            <Timestamp></Timestamp>
            <MulderAgent>
                <MulderCode></MulderCode>
                <MulderName></MulderName>
                <AverageTimePerCase></AverageTimePerCase>
                <TimePeriods>
                    <TimePeriod>
                        <TimePeriodStart></TimePeriodStart>
                        <TimePeriodEnd></TimePeriodEnd>
                        <NumberOfProcessedCases></NumberOfProcessedCases>
                    </TimePeriod>
                    <TimePeriod>...</TimePeriod>
                </TimePeriods>
                <Verdicts>
                    <Verdict>
                        <VerdictType></VerdictType>
                        <NumberOfCases></NumberOfCases>
                    </Verdict>
                    <Verdict>...</Verdict>
                </Verdicts>
            </MulderAgent>
        </RetrieveMulderDetails_Response>
    </soap:Body>
</soap:Envelope>